### PR TITLE
[nim][matmul] use unchecked array

### PR DESCRIPTION
**Pull request by nikhilsimha**
On my machine (Apple M3 Max), the perf difference of using unchecked array vs seq in nim is pretty big (0.51s vs 0.66s)

### CODE REVIEW

**Comment by beef331** [comment]
With `-d:danger --passL:"-flto"` on my machine(ryzen 5600x on linux) on yours I get around 500ms, and on the original I get around 600ms. Which seems to indicate this change only works around lacking LTO and checks on.

**Comment by attractivechaos** [comment]
Somehow with this change, matmul becomes much slower on my Apple M1. N-queens becomes slightly faster. I have reverted matmul.nim to the old version for now.

**Comment by nikhilsimha** [comment]
I see. Must be some mistake on my end - will try to redo the test on m1 mac and see what's going on.

**Comment by nikhilsimha** [comment]
It turns out to be related to compiler flags somehow

with `nim c **-d:release** matmul.nim && time ./matmul`
```
./matmul  **1.48s user** 
./matmul_old  **1.84s user** 
```

with your `nim c **-d:release --bound_checks:off** matmul.nim`
```
./matmul  1.47s 
./matmul_old  0.67s user
```

with  `nim c -d:danger matmul.nim && time ./matmul`
```
./matmul  0.53s 
./matmul_old  0.66s
```

**Comment by beef331** [comment]
To be the fastest you likely should use `--d:danger --passL: "-flto -march=native" --passC: "-flto"`

**Comment by lh3** [comment]
Hmm... I am good with `-d:danger`, but I am hesitant to use the new matmul because it is much slower than the current version under `-d:release`.

**Comment by lh3** [comment]
If you have a version that is faster than the current one under both `-d:release` and `-d:danger`, it will be better.

**Comment by nikhilsimha** [comment]
> faster than the current one under both -d:release and -d:danger

-d:release and -d:danger differ by attached debug information. The rust benchmarks for example also supress debuginfo to be faster. I think the right flag here is -d:danger. I could emulate `-d:danger` with `-d:release` + suppressed debug info if you want.

I am guessing that UnCheckedArray doesn't benefit from a mere "--bound_checks:off" like how the seq does. It seems like an bug / unintended behavior in the compiler. @beef331 probably knows better.

**Comment by beef331** [comment]
`UncheckedArray`s are as the name implies unchecked so they already have no bounds checking. You get roughly the same thing when using `seq[T]` with `--checks:off`

**Comment by attractivechaos** [comment]
The question here is less about compiler options but more about the implementation. If implementation A is faster than B under a more common compiler setting, A is better. Imagine people learn from your implementation but apply `-d:release`. That is not good.

**Comment by nikhilsimha** [comment]
> If implementation A is faster than B under a more common compiler setting, A is better.

Fair point! I myself don't understand why my implementation doesn't improve perf with `release + bounds_off` but with `release` and `danger`. 

I was discussing with folks in the nim discord server and it seems like the right flags to use here are `-d:release -d:lto` I will check if that actually improves the benchmarks.

**Comment by nikhilsimha** [comment]
-d:lto did the trick. I really feel that this (lto) should be the default behavior with -d:release. But I guess that dicussion needs to happen in another forum.

**Comment by nikhilsimha** [comment]
Updated #30 with the recommended flags.

**Comment by beef331** [comment]
This needlessly changes `nqueen` on a ryzen 5600x both `CArray[T]` and `seq[T]` gives same performance with `-d:lto -d:release --panics: on`

**Comment by nikhilsimha** [comment]
> This needlessly changes `nqueen` on a ryzen 5600x both `CArray[T]` and `seq[T]` gives same performance with `-d:lto -d:release --panics: on`
> 
> 

Nqueens was never using seq it was using array. 

(I think nims array defeats the spirit of the problem, the container is supposed to be dynamic. It is also wasteful of memory the way it was before.)

**Comment by attractivechaos** [comment]
Just to confirm that every task is supposed to read "N" from command line:

* nqueen: N is the size of the board. It will take forever to solve 31-queen, so N is 31 at most.
* matmul: size of the matrix
* sudoku: number of repetitions
* bedcov: number of intervals

Nonetheless, learning how to read command line arguments in 20 languages takes time. I was lazy and didn't implement command line parsing in every program.

**Comment by nikhilsimha** [comment]
> Just to confirm that every task is supposed to read "N" from command line:
I see! I can try to address that.

**Pull request merged**
